import React from "react";
import Head from "next/head";

import CyberConnect, { Env } from "@cyberlab/cyberconnect-v2";
import { useAccount, useConnect, useEnsName } from "wagmi";
import { InjectedConnector } from "wagmi/connectors/injected";

export default function Home() {
  const { address, isConnected } = useAccount();
  const [cc, setCC] = React.useState<CyberConnect>();
  const [handle, setHandle] = React.useState("");
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  });

  React.useEffect(() => {
    const cyberConnect = new CyberConnect({
      namespace: "CyberConnect",
      env: Env.STAGING,
      provider: (window as any)?.ethereum,
    });

    setCC(cyberConnect);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {isConnected && address ? (
          <>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                columnGap: 10,
                justifyContent: "center",
                width: 300,
              }}
            >
              <p>Follow handle</p>
              <input
                value={handle}
                onChange={(e) => setHandle(e.target.value)}
              />
            </div>
            <button onClick={() => cc?.follow(address, handle)}>follow</button>
          </>
        ) : (
          <button onClick={() => connect()}>Connect Wallet</button>
        )}
      </main>
    </>
  );
}
