import React from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

import CyberConnect, { Env } from "@cyberlab/cyberconnect-v2";

export default function Home() {
  const [cc, setCC] = React.useState<CyberConnect>();
  const [address, setAddress] = React.useState("");
  const [handle, setHandle] = React.useState("");
  React.useEffect(() => {
    const cyberConnect = new CyberConnect({
      namespace: "CyberConnect",
      env: Env.STAGING,
      provider: (window as any)?.ethereum,
    });
    setCC(cyberConnect);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            columnGap: 10,
            justifyContent: "center",
            width: 300,
          }}
        >
          <p>Address</p>
          <input value={address} onChange={(e) => setAddress(e.target.value)} />
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            columnGap: 10,
            justifyContent: "center",
            width: 300,
          }}
        >
          <p>Follow handle</p>
          <input value={handle} onChange={(e) => setHandle(e.target.value)} />
        </div>
        <button onClick={() => cc?.follow(address, handle)}>follow</button>
      </main>
    </>
  );
}
